### ISSUE TITLE
Can't specify Judgement within Taxon

### ISSUE THREAD

**Issue by nickhaf** [StructuralEquationModels/Taxonomy.jl#11]
Error: 
GFactor(nobserved = Judgement(6, 0.8, missing), nerror_covariances = Judgement(3, 0.7, missing)) 

No error: 
GFactor(nobserved = 6, nerror_covariances = 3)
GFactor(Judgement{Int64, Float64, Missing}(6, 1.0, missing), Judgement{Int64, Float64, Missing}(3, 1.0, missing), Judgement{Int64, Float64, Missing}(0, 1.0, missing), Judgement{Int64, Float64, Missing}(0, 1.0, missing))

-> Gets converted to Judgement, but can't be specified as Judgement directly.

**Comment by aaronpeikert** [comment]
On it.
