### ISSUE TITLE
Mabe add id automatically, so you don't have to copy and paste every time?

### ISSUE THREAD

**Issue by nickhaf** [StructuralEquationModels/Taxonomy.jl#21]

**Comment by aaronpeikert** [comment]
No this is not an oversight but a feature. If the id is added automatically then the record is not self-sufficient. One could think about using the DOI as an id but then one can not update the DOI, or one would have to check it everywhere.
In any case that is what we discussed.

**Comment by nickhaf** [comment]
Ah yes, makes sense.
