### ISSUE TITLE
add CFA taxon

### ISSUE THREAD

**Issue by nickhaf** [StructuralEquationModels/Taxonomy.jl#24]

**Comment by aaronpeikert** [comment]
Could you elaborate a bit? I began the work but then struggled. My idea was that you could compose GFactors:

https://github.com/StructuralEquationModels/Taxonomy.jl/blob/f75706f583f88782ec57a55571085b21c18a95aa/src/taxons/cfa.jl#L1

To build hierachical models:

https://github.com/StructuralEquationModels/Taxonomy.jl/blob/f75706f583f88782ec57a55571085b21c18a95aa/src/taxons/cfa.jl#L17-L20

**Comment by nickhaf** [comment]
I was thinking about cases like 3 factor CFA like conducted here: https://journals.sagepub.com/doi/suppl/10.1177/1073191120905892

Would we compose a GFactor for every Factor and then combine them?

**Comment by aaronpeikert** [comment]
No simply combining will not do, instead we need something that describes how many items are loaded by how many latent variables.

**Comment by nickhaf** [comment]
OK, i will make a proposition ...

**Comment by aaronpeikert** [comment]
I am wondering if it is possible to also code something like bifactor models:

![](https://ars.els-cdn.com/content/image/1-s2.0-B9780123864925000130-f13-02-9780123864925.jpg)
